# ==============================
# APP CONFIG
# ==============================
spring.application.name=backend-springboot
server.port=8080

# ==============================
# MONGODB CONFIG
# ==============================
spring.mongodb.database=omni_price_db
spring.mongodb.host=localhost
spring.mongodb.port=27017
# mongodb://localhost:27017/omni_price_db

# ==============================
# JWT CONFIG
# ==============================
jwt.secret=OmniPriceSecretKeyForJWT2026ProductComparison123456789SecureAuthentication
jwt.expiration=86400000

# ==============================
# PYTHON API CONFIG
# ==============================
python.ai.service.url=http://127.0.0.1:8000/api/search
python.ai.predict.url=http://127.0.0.1:8000/api/predict

# ==============================
# NOTIFICATIONS CONFIG
# ==============================
omni.notifications.monitor.enabled=true
omni.notifications.monitor.interval-ms=300000
omni.notifications.email.enabled=true

# ==============================
# EMAIL (GMAIL SMTP - TLS 587)
# ==============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=mounraj9025@gmail.com
spring.mail.password=sebrirptdzrozzcf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==============================
# OTP EMAIL ENABLE
# ==============================
omni.auth.otp.email.enabled=true

# ==============================
# LOGGING
# ==============================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.security=DEBUG

# venv\Scripts\activate
# uvicorn app:app --reload --port 8000