spring.application.name=backend-springboot
server.port=8080

# MongoDB
spring.mongodb.database=omni_price_db
spring.mongodb.host=localhost
spring.mongodb.port=27017
# mongodb://localhost:27017/omni_price_db

# JWT Configuration
jwt.secret=OmniPriceSecretKeyForJWT2026ProductComparison123456789SecureAuthentication
jwt.expiration=86400000

# Python API
python.ai.service.url=http://127.0.0.1:8000/api/search
python.ai.predict.url=http://127.0.0.1:8000/api/predict

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.security=DEBUG

# cd scraper-service
# venv\Scripts\activate
# uvicorn app:app --reload --port 8000
# python -m spacy download en_core_web_md